BUMPER_TO_CENTER_DIST = 0.17
CAMERA_MODE = 2
CIRCLE_MIN_AREA = 5
CIRCLE_MIN_DISTANCE = 1
CIRCLE_PATTERN_HEIGHT = 3
CIRCLE_PATTERN_WIDTH = 7
TARGET_DIST = 0.20

# Control params
ANGLE_THRESHOLD = 1.5
DISTANCE_THRESHOLD = 0.015
FINAL_ANGLE_THRESHOLD = 2.0
V_CONSTANT = 0.2
V_CORRECTION = 0.75
W_CONSTANT = 0.8
W_CORRECTION = 0.5
